linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
   services:
     - docker
matrix:
   include:
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0
      - <<: *osx
        osx_image: xcode11.2
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
